site_name: AirSim中文文档
repo_url: https://github.com/FrendoWu/AirSim-docs-zh
docs_dir: documents
site_dir: docs
theme: readthedocs
extra:
  version: 1.2.1
nav:
    - "主页": 'README.md'
    - "搭建AirSim":
      - "下载二进制文件": 'use_precompiled.md'
      - "在Windows上构建": 'build_windows.md'
      - "Build on Linux": 'build_linux.md'
      - "Creating Custom Environment": 'unreal_custenv.md'
    - "Using AirSim":
      - "Core APIs": 'apis.md'
      - "Image APIs": 'image_apis.md'
      - "C++ APIs": 'apis_cpp.md'
      - "Development Workflow": 'dev_workflow.md'
      - "Settings": 'settings.md'
      - "Camera Views": 'camera_views.md'      
      - "Using Car": 'using_car.md'
      - "Remote Control": 'remote_control.md'
      - "XBox Controller": 'xbox_controller.md'
      - "Steering Wheel": 'steering_wheel_installation.md'
      - "Multiple Vehicles": 'multi_vehicle.md'
      - "Sensors": 'sensors.md'
      - "LIDAR": 'lidar.md'
      - "ROS": 'ros.md'
      - "Playing Logs": 'playback.md'
    - "Design":
      - "Architecture": 'design.md'
      - "Code Structure": 'code_structure.md'
      - "Coding Guidelines": 'coding_guidelines.md'
      - "Flight Controller": 'flight_controller.md'
      - "Simple Flight": 'simple_flight.md'
      - "Hello Drone": 'hello_drone.md'