site_name: AirSim中文文档
repo_url: https://github.com/FrendoWu/AirSim-docs-zh
docs_dir: documents
site_dir: docs
theme: readthedocs
extra:
  version: 1.2.1
nav:
    - "主页": 'README.md'
    - "搭建AirSim":
      - "下载二进制文件": 'use_precompiled.md'
      - "在Windows上构建": 'build_windows.md'
      - "在Linux上构建": 'build_linux.md'
      - "创建自定义环境": 'unreal_custenv.md'
    - "运行AirSim":
      - "核心APIs": 'apis.md'
      - "图像相关APIs": 'image_apis.md'
      - "C++ APIs": 'apis_cpp.md'
      - "开发工作流程": 'dev_workflow.md'
      - "设置": 'settings.md'
      - "相机视图": 'camera_views.md'      
      - "汽车相关": 'using_car.md'
      - "遥控器控制": 'remote_control.md'
      - "XBox控制": 'xbox_controller.md'
      - "方向盘控制": 'steering_wheel_installation.md'
      - "多车模式": 'multi_vehicle.md'
      - "传感器": 'sensors.md'
      - "LIDAR": 'lidar.md'
      - "ROS": 'ros.md'
      - "运行日志": 'playback.md'
    - "总体设计":
      - "架构": 'design.md'
      - "代码结构": 'code_structure.md'
      - "编码指引": 'coding_guidelines.md'
      - "飞行控制器": 'flight_controller.md'
      - "简单的飞行": 'simple_flight.md'
      - "无人机之你好世界": 'hello_drone.md'
    - "MavLink和PX4":
      - "为AirSim配置PX4": 'px4_setup.md'
      - "PX4之软件在环": 'px4_sitl.md'
      - "为Pixhawk加载AirSim": 'https://youtu.be/1oY8Qu5maQQ'
      - "PX4上配置AirSim": 'https://youtu.be/HNWdYrtw3f0'
      - "调试姿态估计": 'https://www.youtube.com/watch?v=d_FyjKDWQfc&feature=youtu.be'
      - "拦截MavLink的消息": 'https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages'
      - "让无人机于PX4中快速下降": 'https://github.com/Microsoft/AirSim/wiki/Rapid-Descent-on-PX4-drones'
      - "构建PX4": "px4_build.md"
      - "PX4/MavLink日志": 'px4_logging.md'
      - "查看MavLink日志": "log_viewer.md"
    - "升级":
      - "更新虚幻引擎": 'unreal_upgrade.md'
      - "更新APIs": 'upgrade_apis.md'
      - "更新设置": 'upgrade_settings.md'
    - "他人贡献的教程":
      - "强化学习": 'reinforcement_learning.md'
      - "使用市场中的环境": 'https://www.youtube.com/watch?v=y09VbdQWvQY'
      - "简单的碰撞规避算法": 'https://github.com/simondlevy/AirSimTensorFlow'
      - "在Azure上的自动驾驶": 'https://aka.ms/AutonomousDrivingCookbook'
      - "建设Hexacopter": 'https://github.com/Microsoft/AirSim/wiki/hexacopter'
      - "按路径移动演示": 'https://github.com/Microsoft/AirSim/wiki/moveOnPath-demo'
      - "构建点云": 'https://github.com/Microsoft/AirSim/wiki/Point-Clouds'
      - "使用无人机进行测量": 'https://github.com/Microsoft/AirSim/wiki/Implementing-a-Drone-Survey-script'      
    - "杂项":
      - "真实无人机上的AirSim": 'custom_drone.md'
      - "在Linux上安装cmake": 'cmake_linux.md'
      - "关于非固体硬盘的建议": 'hard_drive.md'
      - "pfm格式": 'pfm.md'
      - "设置虚幻环境": 'unreal_proj.md'
      - "Blocks环境": 'unreal_blocks.md'
      - "谁在使用AirSim": 'who_is_using.md'
      - "使用UE插件内容": 'working_with_plugin_contents.md'
      - "方程式赛车的自动驾驶": 'https://github.com/Microsoft/AirSim/wiki/technion'
    - "Support": 
      - "FAQ": 'faq.md'
      - "支持": 'SUPPORT.md'
      - "在GitHub上创建Issue": 'create_issue.md'
      - "贡献": 'CONTRIBUTING.md'