site_name: AirSim中文文档
repo_url: https://github.com/FrendoWu/AirSim-docs-zh
docs_dir: documents
site_dir: docs
theme: readthedocs
extra:
  version: 1.2.1
nav:
    - "主页": 'README.md'
    - "搭建AirSim":
      - "下载二进制文件": 'use_precompiled.md'
      - "在Windows上构建": 'build_windows.md'
      - "Build on Linux": 'build_linux.md'
      - "Creating Custom Environment": 'unreal_custenv.md'
    - "Using AirSim":
      - "Core APIs": 'apis.md'
      - "Image APIs": 'image_apis.md'
      - "C++ APIs": 'apis_cpp.md'
      - "Development Workflow": 'dev_workflow.md'
      - "Settings": 'settings.md'
      - "Camera Views": 'camera_views.md'      
      - "Using Car": 'using_car.md'
      - "Remote Control": 'remote_control.md'
      - "XBox Controller": 'xbox_controller.md'
      - "Steering Wheel": 'steering_wheel_installation.md'
      - "Multiple Vehicles": 'multi_vehicle.md'
      - "Sensors": 'sensors.md'
      - "LIDAR": 'lidar.md'
      - "ROS": 'ros.md'
      - "Playing Logs": 'playback.md'
    - "Design":
      - "Architecture": 'design.md'
      - "Code Structure": 'code_structure.md'
      - "Coding Guidelines": 'coding_guidelines.md'
      - "Flight Controller": 'flight_controller.md'
      - "Simple Flight": 'simple_flight.md'
      - "Hello Drone": 'hello_drone.md'
    - "MavLink and PX4":
      - "PX4 Setup for AirSim": 'px4_setup.md'
      - "PX4 in SITL": 'px4_sitl.md'
      - "AirSim with Pixhawk": 'https://youtu.be/1oY8Qu5maQQ'
      - "PX4 Setup with AirSim": 'https://youtu.be/HNWdYrtw3f0'
      - "Debugging Attitude Estimation": 'https://www.youtube.com/watch?v=d_FyjKDWQfc&feature=youtu.be'
      - "Intercepting MavLink Messages": 'https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages'
      - "Rapid Descent on PX4 Drones": 'https://github.com/Microsoft/AirSim/wiki/Rapid-Descent-on-PX4-drones'
      - "Building PX4": "px4_build.md"
      - "PX4/MavLink Logging": 'px4_logging.md'
      - "MavLink LogViewer": "log_viewer.md"
    - "Upgrading":
      - "Upgrading Unreal": 'unreal_upgrade.md'
      - "Upgrading APIs": 'upgrade_apis.md'
      - "Upgrading Settings": 'upgrade_settings.md'
    - "Contributed Tutorials":
      - "Reinforcement Learning": 'reinforcement_learning.md'
      - "Using Environments from Marketplace": 'https://www.youtube.com/watch?v=y09VbdQWvQY'
      - "Simple Collision Avoidance": 'https://github.com/simondlevy/AirSimTensorFlow'
      - "Autonomous Driving on Azure": 'https://aka.ms/AutonomousDrivingCookbook'
      - "Building Hexacopter": 'https://github.com/Microsoft/AirSim/wiki/hexacopter'
      - "Moving on Path Demo": 'https://github.com/Microsoft/AirSim/wiki/moveOnPath-demo'
      - "Building Point Clouds": 'https://github.com/Microsoft/AirSim/wiki/Point-Clouds'
      - "Surveying Using Drone": 'https://github.com/Microsoft/AirSim/wiki/Implementing-a-Drone-Survey-script'      
    - "Misc":
      - "AirSim on Real Drones": 'custom_drone.md'
      - "Installing cmake on Linux": 'cmake_linux.md'
      - "Tips for Busy HDD": 'hard_drive.md'
      - "pfm format": 'pfm.md'
      - "Setting up Unreal Environment": 'unreal_proj.md'
      - "Blocks Environment": 'unreal_blocks.md'
      - "Who is Using AirSim": 'who_is_using.md'
      - "Working with UE Plugin Contents": 'working_with_plugin_contents.md'
      - "Formula Student Technion Self-drive": 'https://github.com/Microsoft/AirSim/wiki/technion'
    - "Support": 
      - "FAQ": 'faq.md'
      - "Support": 'SUPPORT.md'
      - "Create Issue": 'create_issue.md'
      - "Contribute": 'CONTRIBUTING.md'